### ISSUE TITLE
Additional label/tag for Bodywork

### ISSUE THREAD

**Issue by AlexIoannides** [aporia-ai/mlops.toys#10]
Hello,

Many thanks for including [Bodywork](https://github.com/bodywork-ml/bodywork-core)!

Is it possible to add `Training Orchestration` in addition to `Model Serving`, as we cover both in equal measures?

Many thanks,

Alex

**Comment by SnirShechter** [comment]
Hey @AlexIoannides,

The website currently supports one category only. There's an issue addressing exactly that (#15). If you could contribute that feature, it would be great.

I'll be closing this issue for now, but feel free to reopen once #15 is merged.

**P.S** you can also edit the description to mention that

**Comment by SnirShechter** [comment]
@AlexIoannides 
It's fine, it'll probably be added in the upcoming weeks. Just watch #15 and once it closes submit a PR to add _Training Orchestration_ to **Bodywork** :)

**Comment by AlexIoannides** [comment]
Will do - thanks Snir.
