### ISSUE TITLE
Hello? Is this abandoned? 😅 

### ISSUE THREAD

**Issue by omesser** [aporia-ai/mlops.toys#100]
Hi folks
As I'm still in the MLOps domain I found myself revisiting the site and repo again to add more project(s) (from iterative.ai), but I see open PRs go back over 1y old...

Is this project/website dead? It would be great to either revive or archive it (and kill the website if so) for clarity since some people may still use this to discover MLOps tools.
If you still want to keep this alive but could may be use assistance with PR reviews/curation every now and then, let me know

(CC @SnirShechter @alongubkin)
Thanks!

**Comment by SnirShechter** [comment]
@omesser You're right. We should've maintained it better. We're on it now 👍
