### ISSUE TITLE
Add TerminusDB

### ISSUE THREAD

**Issue by luke-feeney** [aporia-ai/mlops.toys#11]
Suggestion to include TerminusDB in the list of MLOps tooling:

TerminusDB is an open-source graph platform and document store. It is designed for building data-intensive applications and knowledge graphs.

- Quickly build **versioned, bitemporal data products** and give access to your domain teams
- **Visually construct data models**, which are easy, maintainable, and enforced
- Share your work and **collaborate with colleagues**
- Versioning first - **a full audit log, with commit history**. You can see how data has changed, query diffs, and roll-back errors. You can also time-travel to any point in the data's history so you always know what happened. 
- **Data lineage** - where data comes from and how it got here

Link to introductory video: https://youtu.be/RNeYYvYIZbs

[Try TerminusDB](https://github.com/terminusdb/terminusdb)

**Comment by SnirShechter** [comment]
@luke-feeney 
Hey,
You're welcome to add it yourself. If you're having any issues you can contact me directly.

Here's an example of such PRs: #1 , #17

**Comment by luke-feeney** [comment]
Ok - thanks @SnirShechter

**Comment by SnirShechter** [comment]
Closing since the issue is inactive. Feel free to reopen should you choose so.
