### ISSUE TITLE
Add Streamlit

### ISSUE THREAD

**Issue by eafpres** [aporia-ai/mlops.toys#12]
The Streamlit system seems appropriate in at least model serving

https://streamlit.io/

**Comment by SnirShechter** [comment]
Hey @eafpres ,

You're welcome to add it yourself. If you're having any issues you can contact me directly.

Here's an example of such PRs: #1 , #17

**Comment by SnirShechter** [comment]
Closing since the issue is inactive. Feel free to reopen should you choose so.
