### ISSUE TITLE
Add Kedro

### ISSUE THREAD

**Issue by eafpres** [aporia-ai/mlops.toys#14]
I'm not 100% sure it fits your criteria, but I think Kedro would be of interest to people who land here

https://github.com/quantumblacklabs/kedro

**Comment by SnirShechter** [comment]
Hey @eafpres ,

I'm not aware of Kedro, but if you think it's a good fit for MLOps.toys, we'd appreciate it if you add it yourself. It's super simple.

You can see [this PR](https://github.com/aporia-ai/mlops.toys/pull/44) (and [many others](https://github.com/aporia-ai/mlops.toys/pulls?q=)) as a good example.

Thanks!

**Comment by SnirShechter** [comment]
I'm closing this (inactivity). Feel free to reopen.
