### ISSUE TITLE
Add support for multiple categories per project

### ISSUE THREAD

**Issue by omesser** [aporia-ai/mlops.toys#15]
Hi maintainers,
We would like a way to add projects to multiple categories which is not possible today (I'm sure MLRun is not the only one).
I feel like this is a pretty basic need 😄 

This is in the context of https://github.com/aporia-ai/mlops.toys/issues/9
For now I'll add a PR with MLRun in one category

**Comment by SnirShechter** [comment]
@omesser 
Sounds great!

Would you like to contribute that feature yourself?

**Comment by omesser** [comment]
@SnirShechter  - well, not really a JS guy, I gave it a go here though: https://github.com/aporia-ai/mlops.toys/pull/38
Do with that as you will

**Comment by SnirShechter** [comment]
@omesser Sorry for the lack of maintenance by now. Since you closed the PR, I'm closing the issue as well. Feel free to reopen the PR and we'll review shortly after.
