### ISSUE TITLE
Please add Katonic.ai.

### ISSUE THREAD

**Issue by premnaraindas** [aporia-ai/mlops.toys#20]

**Comment by SnirShechter** [comment]
Hey @premnaraindas ,
You're welcome to add it yourself. If you're having any issues you can contact me directly.

Here's an example of such PRs: #1 , #17

**Comment by shourysharma** [comment]
Hey @SnirShechter . 
https://github.com/aporia-ai/mlops.toys/pull/21
This is PR regarding this issue. Awaiting for your response.
Thanks.

**Comment by SnirShechter** [comment]
Closed because issue author is inactive.
