### ISSUE TITLE
New Project/Company recommendation

### ISSUE THREAD

**Issue by blueplastic** [aporia-ai/mlops.toys#45]
I'd like to suggest our company as an addition to the MLOps list.

Name: OctoML
Suggested new category: ML model optimization and acceleration

URL: https://octoml.ai/

Description:
OctoML automatically optimizes machine learning models to deliver up to 30x faster inference or prediction time, without sacrificing accuracy. 

Deep Learning models optimized with our open source Apache TVM technology have less user-perceived lag, maximize hardware utilization, saving deployment costs, and are energy efficient for edge/IoT devices. 

We also comprehensively benchmark customers’ models across CPU, GPU and Accelerator chips to help select the ideal hardware, balancing cost and performance.

How does OctoML speed up your machine learning predictions automatically?
Built on Apache TVM, the OctoML platform does the hard work of automatically making a model production-ready. Our technology uses machine learning to search the space of possible optimizations for a given model, freeing machine learning engineers from having to do it manually using specialized vendor/kernel libraries. It works by running experiments against the target hardware (CPU, GPU etc) to learn how the hardware behaves when certain automatically chosen optimizations are applied. We explore thousands to millions of permutations of a model. When the process is finished, we deliver a fast, energy efficient and accurate model ready to be pushed to production.

Explainer video: https://www.youtube.com/watch?v=gpO4y1mPMWA

**Comment by SnirShechter** [comment]
Hey @blueplastic,

We'd appreciate it if you add it yourself, It's super simple. You can see [this PR](https://github.com/aporia-ai/mlops.toys/pull/44) (and [many others](https://github.com/aporia-ai/mlops.toys/pulls?q=)) as a good example.

Thanks!


**P.S** in which category would you place it?

**Comment by SnirShechter** [comment]
I'm closing this (inactivity). Feel free to reopen.
