### ISSUE TITLE
Add lakeFS

### ISSUE THREAD

**Issue by peacing** [aporia-ai/mlops.toys#50]
Would love to see lakeFS added to this cool project!

Name: lakeFS
Category: Data Versioning
URL: https://lakefs.io

Description:
lakeFS is an open-source data lake management platform that transforms your object storage into a Git-like repository. lakeFS enables you to manage your data lake the way you manage your code. Run parallel pipelines for experimentation and CI/CD for your data.

lakeFS features:
- Exabytes scale version control
- Git-like operations: branch, commit, merge, revert
- Zero copy branching for frictionless experiments
- Full reproducibility of data and code
- Pre-commit/merge hooks for data CI/CD
- Instantly revert changes to data

Getting started video: https://www.youtube.com/watch?v=xThorxDzmrw&t=5s

**Comment by SnirShechter** [comment]
Hey @peacing ,

LakeFS seems like a good fit for MLOps.toys. We'd appreciate it if you add it yourself, It's super simple.

You can see [this PR](https://github.com/aporia-ai/mlops.toys/pull/44) (and [many others](https://github.com/aporia-ai/mlops.toys/pulls?q=)) as a good example.

Thanks!

**Comment by SnirShechter** [comment]
I'm closing this (inactivity). Feel free to reopen.
