### ISSUE TITLE
Missing project request!

### ISSUE THREAD

**Issue by Theo-** [aporia-ai/mlops.toys#6]
Hi, 

We are making it super easy for data scientists to deploy AI at [inferrd.com](https://inferrd.com). We'd love to be included on your website. Can I create a pull request?

**Comment by alongubkin** [comment]
Cool project! Of course :)

**Comment by SnirShechter** [comment]
@Theo- 
I'm gonna close this. Waiting for your PR :)

If you have any problems, feel free to contact me.

**Comment by Theo-** [comment]
@SnirShechter here is the PR https://github.com/aporia-ai/mlops.toys/pull/29 :)
