### ISSUE TITLE
[Request] FuseML - Open Source AI Orchestrato

### ISSUE THREAD

**Issue by alfsuse** [aporia-ai/mlops.toys#69]
Hi there, thanks for this amazing collection of tools and platforms I was wondering if you may add also FuseML. It's a new project I with other 3 are running as incubation project from SUSE and we are looking for help from other contributors.
We got a micro-webiste (https:// fuseml.github.io) and of cource a GH repo (https://github.com/fuseml).

A brief decription for the project:
FuseML allows you to re-use existing components and tools to create and manage the end-to-end ML lifecycle.
Optimize AI workload with a low-code approach and an extensible framework.
Allows teams to quickly iterate and re-use existing, well known tools for rapid experimentation and fast production releases.
It's all about Open Source, MLOps and fast delivery.

Hope this is enough we got also a youtube channel [here](https://www.youtube.com/channel/UCQLoLTikJDDMXvywWd27FBg=)

**Comment by SnirShechter** [comment]
Hey @alfsuse , sorry for the late answer.

You're welcome to add it yourself, it's **really** easy. You can see #73 (or many other PRs) as an example.

If you have any issues, feel free to get in touch with me :)
