### ISSUE TITLE
[Request] Missing project - PrimeHub

### ISSUE THREAD

**Issue by gblpedia** [aporia-ai/mlops.toys#7]
Hi there,

Please help adds the project, PrimeHub.  Many thanks.

PrimeHub, a Kubernetes-based collaborative ML platform for teams of data scientists and administrators.

- Cluster Computing
- One-Click Notebook Environments
- Group-centric Dataset Management / Resources Management / Access-control Management
- Custom Machine Learning Environments
- Model Tracking and Deployment 
- Capability Augmentation with 3rd-party Apps

It equips administrators with group-centric managements and eases MLOps for data scientists with pluggable capabilities.

[Try PrimeHub CE](https://github.com/InfuseAI/primehub)
[Try PrimeHub](https://www.infuseai.io/)

**Comment by SnirShechter** [comment]
Hey @gblpedia,
You're welcome to add it yourself. If you're having any issues you can contact me directly.

Here's an example of such PRs: #1 , #17

**Comment by gblpedia** [comment]
Thank you. will do it.

**Comment by SnirShechter** [comment]
Closed by #22
