### ISSUE TITLE
Adding Modzy 

### ISSUE THREAD

**Issue by kelloyd3** [aporia-ai/mlops.toys#80]
Name: Modzy 
buttonText: Try Modzy 
link: https://www.modzy.com/try-free/
category: Model Monitoring, Model Serving, Experiment Tracking, Explainability
description: >- Modzy is an MLOps platform that accelerates the deployment, integration, and monitoring of production-ready AI. 

Features: 
- Easy model deployment and monitoring for data scientists, with drift detection and explainability 
- APIs and SDKs in Python, Java, Javascript, and Go for developers to integrate AI models into any application 
- Support for cloud, on-premise, edge or hybrid deployments, with military-grade security 

gitHubRepo: https://github.com/modzy
YouTube demo link: https://youtu.be/TluT0ZG-QRM

![MODZY-RGB-POS](https://user-images.githubusercontent.com/88152652/145624360-3bb83420-b1ae-4af9-98cf-86082cf1fece.jpg)

**Comment by bmunday3** [comment]
Hi maintainers,

I just opened this [PR](https://github.com/aporia-ai/mlops.toys/pull/81) with this info to add Modzy to your page. Thank you!

**Comment by SnirShechter** [comment]
Closed by #81
